name: calories_app_new
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.9
  flutter_local_notifications: ^16.3.0
  timezone: ^0.9.2
  google_mobile_ads: ^4.0.0
  crypto: ^3.0.3
  flutter_svg: ^1.1.6
  lottie:  ^3.1.3
  applovin_max: ^3.0.0
  # Dependencias principales de Flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # HTTP y APIs
  http: ^1.2.0
  
  # Environment variables
  flutter_dotenv: ^5.1.0
  
  # Persistencia local
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  
  # State management
  provider: ^6.1.2
  flutter_bloc: ^8.1.3 
  
  # Firebase
  firebase_auth: ^4.15.2
  cloud_firestore: ^4.13.6
  google_sign_in: ^6.1.5
  
  # Multimedia
  image_picker: ^1.0.4
  audioplayers: ^5.0.0
  
  # Utilidades
  vibration: ^1.7.4
  url_launcher: ^6.1.10
  clipboard: ^0.1.3
  
  # UI y gráficos
  fl_chart: ^0.64.0
  just_audio: ^0.9.42
  facebook_audience_network: ^1.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
  # Generadores de código para Hive
  hive_generator: ^2.0.1
  build_runner: ^2.1.5

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/sounds/
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf