name: BetterMe Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  FLUTTER_VERSION: '3.22.3'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true
          cache-key: flutter-${{ env.FLUTTER_VERSION }}

      - name: Install dependencies
        run: flutter pub get

      - name: Create .env file with secrets
        run: |
          cat > .env << EOF
          NUTRITIONIX_APP_ID=${{ secrets.NUTRITIONIX_APP_ID }}
          NUTRITIONIX_APP_KEY=${{ secrets.NUTRITIONIX_APP_KEY }}
          GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
          EOF

      - name: Create google-services.json
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > android/app/google-services.json

      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons

      # ✅ PASO CRUCIAL QUE TE FALTABA: Subir el APK
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: betterme-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7

      # ✅ OPCIONAL: Subir APK split para reducir tamaño
      - name: Upload Split APKs
        uses: actions/upload-artifact@v4
        with:
          name: betterme-split-apks
          path: build/app/outputs/flutter-apk/
          retention-days: 7
