name: DEBUG Profundo - Sin Hive

on: workflow_dispatch

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Crear main.dart de EMERGENCIA
        run: |
          cat > lib/main.dart << 'EOF'
import 'package:flutter/material.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  try {
    await dotenv.load(fileName: '.env');
    print('✅ Variables de entorno cargadas');
    
    runApp(const MyApp());
  } catch (e) {
    print('❌ Error: $e');
    runApp(ErrorApp(error: e.toString()));
  }
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('BetterMe TEST')),
        body: const Center(
          child: Text('✅ APP FUNCIONANDO - Sin Hive', 
            style: TextStyle(fontSize: 20)),
        ),
      ),
    );
  }
}

class ErrorApp extends StatelessWidget {
  final String error;
  const ErrorApp({super.key, required this.error});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Text('ERROR: $error', style: const TextStyle(color: Colors.red)),
        ),
      ),
    );
  }
}
EOF

      - name: Build APK de prueba
        run: flutter build apk --release

      - name: Upload APK de prueba
        uses: actions/upload-artifact@v4
        with:
          name: debug-sin-hive
          path: build/app/outputs/flutter-apk/app-release.apk
